language: go

go:
  - 1.11.x
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - go test -cpu=1,2 -v ./...
  - go test -cover -covermode=count ./...
